"use client";
// Dashboard de KPIs com filtros de período e gráficos comerciais.
import { useState } from "react";
import { Activity, BadgeDollarSign, CalendarClock, HeartHandshake, Percent, Timer, UserPlus, Users } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { KpiCard } from "@/components/metrics/KpiCard";
import { ConversionFunnel } from "@/components/metrics/ConversionFunnel";
import { RevenueChart } from "@/components/metrics/RevenueChart";
import { useMetrics } from "@/hooks/useMetrics";
import { money } from "@/lib/utils";
import { EmptyState } from "@/components/ui/EmptyState";
export default function MetricsPage(){const [days,setDays]=useState(30);const {data}=useMetrics(days);return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="label">Inteligência comercial</p><h1 className="mt-1 text-3xl font-semibold">Métricas</h1><p className="mt-1 text-sm text-slate-500">Resultados consolidados da operação.</p></div><div className="flex gap-2"><select value={days} onChange={e=>setDays(Number(e.target.value))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value={7}>Últimos 7 dias</option><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 3 meses</option><option value={365}>Últimos 12 meses</option></select><select className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option>Todos os corretores</option></select></div></div>
<div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Leads gerados" value={String(data.leads)} icon={UserPlus}/><KpiCard label="Taxa de qualificação" value={`${data.qualificationRate.toFixed(1)}%`} icon={Percent}/><KpiCard label="Taxa de fechamento" value={`${data.closingRate.toFixed(1)}%`} icon={HeartHandshake}/><KpiCard label="Ticket médio" value={money(data.averageTicket)} icon={BadgeDollarSign}/><KpiCard label="Receita total" value={money(data.revenue)} icon={Activity}/><KpiCard label="Vidas ativas" value={String(data.activeLives)} icon={Users}/><KpiCard label="Churn mensal" value={`${data.churnRate}%`} icon={CalendarClock}/><KpiCard label="Tempo de fechamento" value={`${data.averageClosingDays} dias`} icon={Timer}/></div>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-6"><h2 className="text-lg font-semibold">Funil de conversão</h2><p className="mb-4 text-sm text-slate-500">Volume de leads em cada etapa</p>{data.leads?<ConversionFunnel/>:<EmptyState title="Sem dados para o funil" text="O gráfico será exibido quando houver leads cadastrados."/>}</Card><Card className="p-6"><h2 className="text-lg font-semibold">Receita por mês</h2><p className="mb-4 text-sm text-slate-500">Evolução nos últimos 12 meses</p>{data.revenue?<RevenueChart/>:<EmptyState title="Sem receita registrada" text="O gráfico será exibido quando houver propostas aceitas."/>}</Card></div></>;}
