"use client";
// Painel proprietário para contas, métricas, disponibilidade e atualizações.
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, Eye, EyeOff, LockKeyhole, Plus, Power, RefreshCw, ShieldCheck, Target, Trash2, UserCheck, UserX, Users } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { money } from "@/lib/utils";

type Account={id:string;name:string;email:string;role:"ADMIN"|"CORRETOR";active:boolean;crmEnabled:boolean;createdAt:string;lastLoginAt?:string;metrics:{leads:number;qualified:number;closed:number;revenue:number;target:number;current:number;averageTicket:number};insight:{status:string;label:string;message:string}};
type Data={settings:{crmEnabled:boolean;updatePolicy:"AUTOMATIC"|"ON_COMPLETION";maintenanceMessage:string;updatedAt:string};accounts:Account[]};
const insightStyle:Record<string,string>={ON_TRACK:"bg-emerald-50 text-emerald-700",DIFFICULTY:"bg-red-50 text-red-700",BEHIND:"bg-amber-50 text-amber-700",NO_DATA:"bg-slate-100 text-slate-600"};

export default function AdminPage(){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [creating,setCreating]=useState(false);const [showPassword,setShowPassword]=useState(false);const [selected,setSelected]=useState<Account|null>(null);
 const load=useCallback(async()=>{setError("");const response=await fetch("/api/admin/accounts");const body=await response.json();if(!response.ok)throw new Error(body.error||"Falha ao carregar painel.");setData(body);},[]);
 useEffect(()=>{load().catch((err:Error)=>setError(err.message));},[load]);
 const brokers=useMemo(()=>data?.accounts.filter(item=>item.role==="CORRETOR")||[],[data]);
 const summary=useMemo(()=>({active:brokers.filter(item=>item.active&&item.crmEnabled).length,disabled:brokers.filter(item=>!item.active||!item.crmEnabled).length,onTrack:brokers.filter(item=>item.insight.status==="ON_TRACK").length,difficulty:brokers.filter(item=>["DIFFICULTY","BEHIND"].includes(item.insight.status)).length}),[brokers]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),password:form.get("password"),target:Number(form.get("target")||0)})});const body=await response.json();if(!response.ok){setError(body.error||"Não foi possível criar a conta.");return}setCreating(false);await load();}
 async function patch(id:string,changes:Record<string,unknown>){const response=await fetch(`/api/admin/accounts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});if(!response.ok){const body=await response.json();setError(body.error);return}setSelected(null);await load();}
 async function remove(id:string){if(!window.confirm("Excluir permanentemente esta conta de corretor?"))return;const response=await fetch(`/api/admin/accounts/${id}`,{method:"DELETE"});if(!response.ok){setError("Não foi possível excluir a conta.");return}setSelected(null);await load();}
 async function settings(changes:Record<string,unknown>){const response=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});if(!response.ok){setError("Não foi possível salvar a configuração.");return}await load();}
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="label">Acesso proprietário</p><h1 className="mt-1 text-3xl font-semibold">Painel administrativo</h1><p className="mt-1 text-sm text-slate-500">Contas, desempenho, disponibilidade e publicação do CRM.</p></div><Button onClick={()=>setCreating(value=>!value)}><Plus size={17}/>Nova conta</Button></div>
 {error&&<div className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Corretores" value={String(brokers.length)}/><Metric icon={UserCheck} label="Com acesso" value={String(summary.active)}/><Metric icon={CheckCircle2} label="Batendo a meta" value={String(summary.onTrack)}/><Metric icon={AlertTriangle} label="Precisam de atenção" value={String(summary.difficulty)}/></div>
 {creating&&<Card className="mt-6 p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-brand-600"/><div><h2 className="font-semibold">Registrar nova conta</h2><p className="text-sm text-slate-500">O corretor poderá entrar assim que a conta for criada.</p></div></div><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Nome<input name="name" required minLength={2} className="mt-2 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-medium">E-mail<input name="email" required type="email" className="mt-2 h-10 w-full rounded-lg border px-3"/></label><label className="text-sm font-medium">Senha inicial<span className="relative mt-2 block"><input name="password" required minLength={8} type={showPassword?"text":"password"} className="h-10 w-full rounded-lg border px-3 pr-10"/><button type="button" onClick={()=>setShowPassword(value=>!value)} className="absolute inset-y-0 right-0 grid w-10 place-items-center text-slate-400" aria-label={showPassword?"Ocultar senha":"Mostrar senha"}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><label className="text-sm font-medium">Meta mensal<input name="target" type="number" min="0" step="100" defaultValue="0" className="mt-2 h-10 w-full rounded-lg border px-3"/></label><div className="flex gap-2 md:col-span-2"><Button type="submit">Criar conta</Button><Button type="button" variant="secondary" onClick={()=>setCreating(false)}>Cancelar</Button></div></form></Card>}
 {data&&<div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Corretores</h2><p className="text-sm text-slate-500">Clique em um nome para ver o desempenho detalhado.</p></div>{brokers.length?<div className="divide-y">{brokers.map(account=><button key={account.id} onClick={()=>setSelected(account)} className="flex w-full items-center gap-4 p-5 text-left hover:bg-slate-50"><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-50 text-xs font-bold text-brand-700">{account.name.split(" ").map(word=>word[0]).slice(0,2)}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{account.name}</strong><span className="text-xs text-slate-500">{account.email}</span></span><span className={`rounded-md px-2 py-1 text-[11px] font-semibold ${insightStyle[account.insight.status]||insightStyle.NO_DATA}`}>{account.insight.label}</span><span className={`text-xs font-semibold ${account.active&&account.crmEnabled?"text-emerald-600":"text-red-600"}`}>{account.active&&account.crmEnabled?"Ativo":"Bloqueado"}</span></button>)}</div>:<EmptyState title="Nenhum corretor registrado" text="Crie a primeira conta para iniciar a gestão da equipe."/>}</Card>
 <Card className="p-6"><div className="flex items-center gap-2"><Power className={data.settings.crmEnabled?"text-emerald-600":"text-red-600"}/><h2 className="font-semibold">Disponibilidade do CRM</h2></div><p className="mt-2 text-sm text-slate-500">O administrador sempre mantém acesso durante uma manutenção.</p><div className="mt-5 flex items-center justify-between rounded-lg border p-4"><div><strong className="text-sm">CRM para corretores</strong><p className="text-xs text-slate-500">{data.settings.crmEnabled?"Disponível para a equipe":"Modo manutenção ativo"}</p></div><button role="switch" aria-checked={data.settings.crmEnabled} onClick={()=>settings({crmEnabled:!data.settings.crmEnabled})} className={`relative h-7 w-12 rounded-full ${data.settings.crmEnabled?"bg-emerald-500":"bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${data.settings.crmEnabled?"left-6":"left-1"}`}/></button></div><label className="mt-5 block text-sm font-medium">Publicação de atualizações<select value={data.settings.updatePolicy} onChange={event=>settings({updatePolicy:event.target.value})} className="mt-2 h-10 w-full rounded-lg border bg-white px-3"><option value="ON_COMPLETION">Somente quando finalizadas</option><option value="AUTOMATIC">Publicar automaticamente</option></select></label><label className="mt-4 block text-sm font-medium">Mensagem de manutenção<textarea defaultValue={data.settings.maintenanceMessage} onBlur={event=>settings({maintenanceMessage:event.target.value})} rows={3} className="mt-2 w-full rounded-lg border p-3 text-sm"/></label></Card></div>}
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5" onMouseDown={event=>{if(event.currentTarget===event.target)setSelected(null)}}><Card className="w-full max-w-2xl p-6"><div className="flex items-start justify-between"><div><p className="label">Desempenho individual</p><h2 className="mt-1 text-2xl font-semibold">{selected.name}</h2><p className="text-sm text-slate-500">{selected.email}</p></div><Button variant="ghost" onClick={()=>setSelected(null)}>Fechar</Button></div><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Small label="Leads" value={String(selected.metrics.leads)}/><Small label="Qualificados" value={String(selected.metrics.qualified)}/><Small label="Fechados" value={String(selected.metrics.closed)}/><Small label="Receita" value={money(selected.metrics.revenue)}/></div><div className={`mt-5 rounded-xl p-4 ${insightStyle[selected.insight.status]||insightStyle.NO_DATA}`}><strong className="text-sm">Análise de desempenho: {selected.insight.label}</strong><p className="mt-1 text-sm">{selected.insight.message}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button variant="secondary" onClick={()=>patch(selected.id,{crmEnabled:!selected.crmEnabled})}><Power size={16}/>{selected.crmEnabled?"Desligar CRM deste corretor":"Liberar CRM deste corretor"}</Button><Button variant="secondary" onClick={()=>patch(selected.id,{active:!selected.active})}>{selected.active?<UserX size={16}/>:<UserCheck size={16}/>} {selected.active?"Desativar conta":"Reativar conta"}</Button><Button variant="danger" className="sm:col-span-2" onClick={()=>remove(selected.id)}><Trash2 size={16}/>Excluir conta permanentemente</Button></div></Card></div>}</>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <Card className="p-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-brand-50 text-brand-600"><Icon size={18}/></span><p className="mt-4 text-2xl font-semibold">{value}</p><p className="text-sm text-slate-500">{label}</p></Card>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
