"use client";
// Pipeline em tabela com filtros, ordenação e ações em massa.
import { useMemo, useState } from "react";
import { Filter, Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { LeadsTable } from "@/components/pipeline/LeadsTable";
import { useLeads } from "@/hooks/useLeads";
export default function PipelinePage(){const {data}=useLeads();const [search,setSearch]=useState("");const [temperature,setTemperature]=useState("TODAS");const [order,setOrder]=useState("score");const leads=useMemo(()=>data.filter(l=>(l.name+l.phone).toLowerCase().includes(search.toLowerCase())&&(temperature==="TODAS"||l.temperature===temperature)).sort((a,b)=>order==="name"?a.name.localeCompare(b.name):order==="value"?Number(b.estimatedValue)-Number(a.estimatedValue):b.score-a.score),[data,search,temperature,order]);
return <><div><p className="label">Operação comercial</p><h1 className="mt-1 text-3xl font-semibold">Pipeline</h1><p className="mt-1 text-sm text-slate-500">Oportunidades priorizadas por intenção e valor.</p></div>
<div className="mt-7 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou telefone" className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm"/></div><select className="h-10 rounded-lg border border-slate-200 px-3 text-sm"><option>Todas as etapas</option><option>Qualificado</option><option>Proposta enviada</option></select><select value={temperature} onChange={e=>setTemperature(e.target.value)} className="h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="TODAS">Todas as temperaturas</option><option value="QUENTE">Quentes</option><option value="MORNO">Mornos</option><option value="FRIO">Frios</option></select><select value={order} onChange={e=>setOrder(e.target.value)} className="h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="score">Score ↓</option><option value="value">Valor estimado ↓</option><option value="name">Nome A–Z</option></select><Button variant="secondary"><SlidersHorizontal size={16}/>Mais filtros</Button></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><strong className="text-sm">{leads.length} leads encontrados</strong><span className="text-xs text-slate-500">Atualizado há poucos segundos</span></div></div><div className="mt-4"><LeadsTable leads={leads}/></div></>;}

