"use client";
// Lista pesquisável e filtrável de conversas do WhatsApp.
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { Conversation } from "@/types";
import { SentimentIndicator } from "@/components/shared/SentimentIndicator";
import { cn } from "@/lib/utils";
export function ConversationList({items,activeId,onSelect}:{items:Conversation[];activeId?:string;onSelect:(id:string)=>void}){const [search,setSearch]=useState("");const [filter,setFilter]=useState("Todas");const list=useMemo(()=>items.filter(c=>c.lead.name.toLowerCase().includes(search.toLowerCase())&&(filter==="Todas"||filter==="Urgente"?filter!=="Urgente"||c.sentiment==="URGENTE":c.status===filter.toUpperCase())),[items,search,filter]);
return <aside className="flex w-full shrink-0 flex-col border-r border-slate-200 bg-white lg:w-[360px]"><div className="border-b p-4"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm" placeholder="Buscar conversa"/></div><div className="mt-3 flex gap-1">{["Todas","Bot","Humano","Urgente"].map(item=><button key={item} onClick={()=>setFilter(item)} className={cn("rounded-full px-3 py-1.5 text-xs font-medium",filter===item?"bg-slate-900 text-white":"bg-slate-100 text-slate-600")}>{item}</button>)}</div></div>
<div className="scrollbar flex-1 overflow-y-auto">{list.map(c=>{const last=c.messages[c.messages.length-1];return <button key={c.id} onClick={()=>onSelect(c.id)} className={cn("flex w-full gap-3 border-b border-slate-100 p-4 text-left transition hover:bg-slate-50",activeId===c.id&&"border-l-2 border-l-brand-600 bg-brand-50/50")}><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-slate-200 text-xs font-bold">{c.lead.name.split(" ").map(w=>w[0]).slice(0,2)}</span><span className="min-w-0 flex-1"><span className="flex justify-between gap-2"><strong className="truncate text-sm">{c.lead.name}</strong><span className="whitespace-nowrap text-[10px] text-slate-400">{new Date(c.updatedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></span><span className="mt-1 block truncate text-xs text-slate-500">{last?.content}</span><span className="mt-2 block"><SentimentIndicator value={c.sentiment}/></span></span>{c.sentiment==="URGENTE"&&<span className="grid h-5 min-w-5 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-bold text-white">2</span>}</button>})}</div></aside>;}

