// Bolha de mensagem com variações para lead, bot e corretor, incluindo áudio.
import { ExternalLink, FileText, ImageIcon, Mic } from "lucide-react";
import { Message } from "@/types";
import { cn } from "@/lib/utils";
export function MessageBubble({message}:{message:Message}){const incoming=message.sender==="LEAD";return <div className={cn("flex",incoming?"justify-start":"justify-end")}><div className={cn("max-w-[76%] rounded-2xl px-4 py-3 text-sm leading-6",incoming?"rounded-bl-md bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-100":message.sender==="BOT"?"rounded-br-md border border-blue-100 bg-brand-50 text-slate-800 dark:border-brand-900 dark:bg-brand-950/40 dark:text-slate-100":"rounded-br-md bg-brand-600 text-white")}>
{message.type==="AUDIO"&&<div className="mb-2"><div className="mb-2 flex items-center gap-2 font-semibold"><Mic size={16}/>Mensagem de áudio</div>{message.mediaUrl&&<audio controls preload="none" src={message.mediaUrl} className="h-10 max-w-full"/>}</div>}
{message.type==="IMAGE"&&<div className="mb-2">{message.mediaUrl?<a href={message.mediaUrl} target="_blank" rel="noreferrer"><img src={message.mediaUrl} alt="Imagem recebida pelo WhatsApp" className="max-h-80 rounded-xl object-contain"/></a>:<div className="flex items-center gap-2 font-semibold"><ImageIcon size={16}/>Imagem</div>}</div>}
{message.type==="DOCUMENT"&&<div className="mb-2 flex items-center gap-2 font-semibold"><FileText size={16}/>{message.mediaUrl?<a href={message.mediaUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 underline">Abrir arquivo<ExternalLink size={13}/></a>:"Documento"}</div>}
<p>{message.content}</p>{message.transcription&&<details className="mt-2 border-t border-current/10 pt-2"><summary className="cursor-pointer text-xs font-semibold">Ver transcrição</summary><p className="mt-1 text-xs">{message.transcription}</p></details>}<p className={cn("mt-1 text-right text-[10px]",incoming?"text-slate-400":"text-current/60")}>{new Date(message.sentAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</p></div></div>}

