"use client";
// Mini planilha editável com validação local, duplicidade remota e importação parcial.
import { useMemo, useState } from "react";
import { AlertTriangle, Plus, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/Button";
import type { Operator } from "./OperatorTable";

type Stage="NOVO"|"QUALIFICADO"|"PROPOSTA_ENVIADA"|"EM_ANALISE"|"NEGOCIACAO"|"FECHADO"|"PERDIDO";
type Row={id:string;name:string;phone:string;operator:string;livesCount:number;estimatedValue:string;stage:Stage;notes:string};
type Result={created:number;skipped:number;errors:Array<{line:number;reason:string}>};
const stages:Stage[]=["NOVO","QUALIFICADO","PROPOSTA_ENVIADA","EM_ANALISE","NEGOCIACAO","FECHADO","PERDIDO"];
const makeRow=():Row=>({id:crypto.randomUUID(),name:"",phone:"",operator:"",livesCount:1,estimatedValue:"",stage:"NOVO",notes:""});

export function BulkImportGrid({operators}:{operators:Operator[]}){
 const[rows,setRows]=useState<Row[]>(()=>Array.from({length:10},makeRow));const[errors,setErrors]=useState<Record<number,string>>({});const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(false);const[confirmClear,setConfirmClear]=useState(false);
 const filled=useMemo(()=>rows.filter(row=>row.name.trim()||row.phone.trim()),[rows]);
 function update(index:number,key:keyof Row,value:string|number){setRows(current=>current.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row));setErrors(current=>{const next={...current};delete next[index];return next})}
 async function validate(){const next:Record<number,string>={};const seen=new Set<string>();filled.forEach(row=>{const index=rows.indexOf(row);const phone=row.phone.replace(/\D/g,"");if(!row.name.trim())next[index]="Nome é obrigatório";else if(phone.length<10)next[index]="WhatsApp inválido";else if(seen.has(phone))next[index]="WhatsApp duplicado nesta planilha";seen.add(phone)});if(filled.length){const params=new URLSearchParams();filled.forEach(row=>params.append("phone",row.phone));const response=await fetch(`/api/admin/leads/bulk-create?${params}`);if(response.ok){const body=await response.json() as {existing:string[]};const existingDigits=new Set(body.existing.map(phone=>phone.replace(/\D/g,"")));filled.forEach(row=>{const index=rows.indexOf(row);let digits=row.phone.replace(/\D/g,"");if(!digits.startsWith("55"))digits=`55${digits}`;if(existingDigits.has(digits))next[index]="Este número já existe no sistema"})}}setErrors(next);return Object.keys(next).length===0}
 async function submit(){setLoading(true);setResult(null);try{if(!await validate())return;const response=await fetch("/api/admin/leads/bulk-create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leads:filled.map(row=>({...row,estimatedValue:row.estimatedValue?Number(row.estimatedValue):undefined}))})});const body=await response.json() as Result&{error?:string};if(!response.ok)throw new Error(body.error||"Falha na importação");setResult(body);const failed=new Set(body.errors.map(item=>item.line-1));setRows(current=>current.filter((_,index)=>failed.has(index)));if(!body.errors.length)setRows(Array.from({length:10},makeRow))}catch(error){setResult({created:0,skipped:filled.length,errors:[{line:0,reason:error instanceof Error?error.message:"Falha na importação"}]})}finally{setLoading(false)}}
 return <div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">#</th><th>Nome *</th><th>WhatsApp *</th><th>Operadora atual</th><th>Vidas</th><th>Valor mensal</th><th>Etapa</th><th>Anotações</th><th/></tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={row.id} className={errors[index]?"bg-red-50":""}><td className="px-3">{index+1}{errors[index]&&<span title={errors[index]}><AlertTriangle className="ml-1 inline text-red-500" size={14}/></span>}</td><Cell><input aria-label={`Nome linha ${index+1}`} value={row.name} onChange={event=>update(index,"name",event.target.value)} className="grid-input"/></Cell><Cell><input aria-label={`WhatsApp linha ${index+1}`} value={row.phone} onChange={event=>update(index,"phone",event.target.value)} placeholder="(22) 99999-9999" className="grid-input"/></Cell><Cell><select value={row.operator} onChange={event=>update(index,"operator",event.target.value)} className="grid-input"><option value="">Nenhuma / Prospect</option>{operators.filter(item=>item.active).map(item=><option key={item.id}>{item.name}</option>)}</select></Cell><Cell><input type="number" min={1} value={row.livesCount} onChange={event=>update(index,"livesCount",Number(event.target.value))} className="grid-input w-20"/></Cell><Cell><input type="number" min={0} step="0.01" value={row.estimatedValue} onChange={event=>update(index,"estimatedValue",event.target.value)} placeholder="R$" className="grid-input w-32"/></Cell><Cell><select value={row.stage} onChange={event=>update(index,"stage",event.target.value)} className="grid-input">{stages.map(stage=><option key={stage}>{stage}</option>)}</select></Cell><Cell><input value={row.notes} onChange={event=>update(index,"notes",event.target.value)} className="grid-input"/></Cell><td><button aria-label={`Remover linha ${index+1}`} onClick={()=>setRows(current=>current.filter((_,rowIndex)=>rowIndex!==index))} className="p-2 text-slate-400 hover:text-red-600"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>
 <div className="mt-4 flex flex-wrap gap-3"><Button variant="secondary" disabled={rows.length>=50} onClick={()=>setRows(current=>[...current,makeRow()])}><Plus size={16}/>Adicionar linha</Button><Button variant="secondary" onClick={validate}>Validar tudo</Button><Button disabled={!filled.length||loading} onClick={submit}><Upload size={16}/>{loading?"Importando...":`Importar ${filled.length} contatos`}</Button><Button variant="danger" onClick={()=>setConfirmClear(true)}>Limpar tudo</Button></div>
 {result&&<div className={`mt-4 rounded-xl border p-4 text-sm ${result.created?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`}><strong>{result.created} contatos importados, {result.skipped} ignorados.</strong>{result.errors.length>0&&<ul className="mt-2 list-disc pl-5">{result.errors.map((error,index)=><li key={`${error.line}-${index}`}>{error.line?`Linha ${error.line}: `:""}{error.reason}</li>)}</ul>}</div>}
 {confirmClear&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="font-semibold">Limpar toda a planilha?</h3><p className="mt-2 text-sm text-slate-500">Os dados ainda não importados serão apagados.</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setConfirmClear(false)}>Cancelar</Button><Button variant="danger" onClick={()=>{setRows(Array.from({length:10},makeRow));setErrors({});setResult(null);setConfirmClear(false)}}>Limpar</Button></div></div></div>}
 </div>;
}
function Cell({children}:{children:React.ReactNode}){return <td className="p-1.5">{children}</td>}
