// Tabela de desempenho dos corretores com mini semáforo de meta.
import { money } from "@/lib/utils";

export type TeamMember={id:string;name:string;avatarUrl:string|null;active:boolean;activeLeads:number;closedThisMonth:number;revenueThisMonth:number;goal:{target:number;current:number;color:"red"|"yellow"|"green";percentage:number}|null;avgResponseTime:number;conversionRate:number};
const goalColor={red:"bg-red-500",yellow:"bg-amber-500",green:"bg-emerald-500"};

export function TeamRankingTable({users}:{users:TeamMember[]}) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-900"><tr><th className="px-5 py-3">Corretor</th><th>Leads ativos</th><th>Fechados</th><th>Receita</th><th>Meta</th><th>Conversão</th><th>Resposta</th></tr></thead><tbody className="divide-y dark:divide-slate-800">{users.map(user=><tr key={user.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-900/70"><td className="px-5 py-4"><span className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-brand-100 text-xs font-bold text-brand-800">{user.name.split(" ").map(word=>word[0]).slice(0,2)}</span><span><strong className="block">{user.name}</strong><small className={user.active?"text-emerald-600":"text-red-600"}>{user.active?"Ativo":"Bloqueado"}</small></span></span></td><td>{user.activeLeads}</td><td>{user.closedThisMonth}</td><td className="font-semibold">{money(user.revenueThisMonth)}</td><td>{user.goal?<span className="flex items-center gap-2"><span className="h-2 w-20 overflow-hidden rounded-full bg-slate-100"><span className={`block h-full ${goalColor[user.goal.color]}`} style={{width:`${Math.min(100,user.goal.percentage)}%`}}/></span><small>{user.goal.percentage.toFixed(0)}%</small></span>:<span className="text-slate-400">Sem meta</span>}</td><td>{user.conversionRate.toFixed(1)}%</td><td>{user.avgResponseTime} min</td></tr>)}</tbody></table></div>;
}
